name: prueba
on:
  push:
    branches: [validation-spokes]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2 # create a checkout (pull repository) in the runner working_dir (usually _work)
      - id: foo
        uses: actions/ztp-pipeline-relocatable@v1
      - run: echo steps-number ${{ steps.foo.outputs.steps-numbers }}
        shell: bash