name: prueba
on:
  push:
    branches: [validation-spokes]

jobs:
  get-lines:
    runs-on: ubuntu-latest
    outputs:
      spokes: ${{ steps.generate-matrix.outputs.spokes }}
    steps:
      - name: Generate Matrix
        id: generate-matrix
        shell: bash
        run: |
          SPOKES='${{ wc -l ./examples/config.yaml }}'
          echo ::set-output name=spokes::${SPOKES}
          
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2 # create a checkout (pull repository) in the runner working_dir (usually _work)
     