name: prueba
on:
  workflow_dispatch:
    inputs:
      RUNNER:
        description: 'GitHub Action Runner Tag'
        required: true

jobs:
  get-lines:
    runs-on: ${{github.event.inputs.RUNNER}}
    outputs:
      spokes: ${{ steps.generate-matrix.outputs.spokes }}
    steps:
      - name: Generate Matrix
        id: generate-matrix
        shell: bash
        run: |
          SPOKES=$(wc -l ./examples/config.yaml)
          echo ::set-output name=spokes::${SPOKES}

  hello_world_job:
    runs-on: ${{github.event.inputs.RUNNER}}
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2 # create a checkout (pull repository) in the runner working_dir (usually _work)
     