name: prueba
on:
  push:
    branches: [validation-spokes]

jobs:
  # ------------------------
  say_hello:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.generate-matrix.outputs.services }}
    steps:
      - uses: actions/checkout@v2 # create a checkout (pull repository) in the runner working_dir (usually _work)
      - run: git pull origin ${GITHUB_REF##*/}

      - name: Generate Matrix
        id: generate-matrix
        run: |
          sudo snap install yq
      
          echo "::set-output name=services::$(cat examples/config.yaml | yq e '.spokes.[] | keys | join(",")' - | jq -Rsc '. / "\n" - [""]')"
          

  # ------------------------
  my_matrix:
    runs-on: ubuntu-latest
    needs:
      - say_hello
    strategy:
      matrix:
        service: ${{ fromJSON(needs.say_hello.outputs.services) }}
    steps:
      - uses: actions/checkout@v2 # create a checkout (pull repository) in the runner working_dir (usually _work)
      - run: git pull origin ${GITHUB_REF##*/}

      - name: Matrix => (${{ matrix.service }}
        run: |
          echo ${{ matrix.service }}
        