name: prueba
on:
  push:
    branches: [validation-spokes]

jobs:
  # ------------------------
  say_hello:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.generate-matrix.outputs.services }}
      versions: ${{ steps.generate-matrix.outputs.versions }}
    steps:
      - name: Generate Matrix
        id: generate-matrix
        run: |
          SERVICES=$(wc -l /etc/hosts)
          echo ::set-output name=services::${SERVICES}
          VERSIONS=$(wc -l /etc/profile)
          echo ::set-output name=versions::${VERSIONS}
  # ------------------------
  my_echo:
    runs-on: ubuntu-latest
    needs:
      - say_hello
    steps:
      - name: Echo previous outputs
        run: echo "${{ toJSON(needs.say_hello.outputs) }}"
  # ------------------------
  my_matrix:
    runs-on: ubuntu-latest
    needs:
      - my_echo
      - say_hello
    strategy:
      matrix:
        service: ${{ fromJSON(needs.say_hello.outputs.services) }}
        version: ${{ fromJSON(needs.say_hello.outputs.versions) }}
    steps:
      - name: Matrix => (${{ matrix.service }} ${{ matrix.version}})
        run: |
          echo ${{ matrix.service }}
          echo ${{ matrix.version }}